#!/usr/bin/env python3
"""Export an MLP policy (ONNX) to a C header for firmware/src/policy.cpp.

    python tools/onnx_to_header.py <policy.onnx> <out.h> [--name label]

Understands the two exporters seen in the duck projects:
  * Microduck (torch):   Sub(mean) -> Div(std) -> [Gemm -> Elu]* -> Gemm
  * Open Duck Mini (tf): Sub(mean) -> Mul(1/std) -> [Gemm -> Sigmoid -> Mul]* -> Gemm -> Split -> Tanh
Weights are emitted row-major [out][in] as const float arrays (they live in flash on the ESP32).
"""
import sys, argparse, numpy as np, onnx
from onnx import numpy_helper

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('onnx'); ap.add_argument('out'); ap.add_argument('--name', default=None)
    a = ap.parse_args()
    m = onnx.load(a.onnx); g = m.graph
    consts = {i.name: numpy_helper.to_array(i) for i in g.initializer}
    for n in g.node:
        if n.op_type == 'Constant':
            consts[n.output[0]] = numpy_helper.to_array(n.attribute[0].t)
    inp = g.input[0]; in_dim = [d.dim_value for d in inp.type.tensor_type.shape.dim][-1]
    out_dim = [d.dim_value for d in g.output[0].type.tensor_type.shape.dim][-1]
    mean = np.zeros(in_dim, np.float32); scale = np.ones(in_dim, np.float32)
    layers = []; act = None; out_tanh = False; split = False
    cur = inp.name
    by_input = {}
    for n in g.node:
        for i in n.input: by_input.setdefault(i, []).append(n)
    nodes = list(g.node)
    # walk in topological (file) order following the running tensor
    for n in nodes:
        if cur not in n.input: continue
        others = [i for i in n.input if i != cur]
        if n.op_type == 'Sub' and others and others[0] in consts:
            mean = consts[others[0]].reshape(-1).astype(np.float32); cur = n.output[0]
        elif n.op_type == 'Div' and others and others[0] in consts:
            scale = (1.0 / consts[others[0]].reshape(-1)).astype(np.float32); cur = n.output[0]
        elif n.op_type == 'Mul' and others and others[0] in consts and consts[others[0]].size == in_dim and not layers:
            scale = consts[others[0]].reshape(-1).astype(np.float32); cur = n.output[0]
        elif n.op_type == 'Gemm':
            W = consts[n.input[1]]; b = consts[n.input[2]]
            transB = next((at.i for at in n.attribute if at.name == 'transB'), 0)
            W = W if transB else W.T           # -> [out][in]
            layers.append((W.astype(np.float32), b.reshape(-1).astype(np.float32))); cur = n.output[0]
        elif n.op_type == 'MatMul':
            W = consts[n.input[1]].T; layers.append((W.astype(np.float32), np.zeros(W.shape[0], np.float32))); cur = n.output[0]
        elif n.op_type == 'Add' and layers and others and others[0] in consts:
            W, b = layers[-1]; layers[-1] = (W, b + consts[others[0]].reshape(-1)); cur = n.output[0]
        elif n.op_type == 'Elu': act = 0; cur = n.output[0]
        elif n.op_type == 'Relu': act = 2; cur = n.output[0]
        elif n.op_type == 'Sigmoid':
            # swish pattern: Mul(x, Sigmoid(x))
            mul = next((k for k in by_input.get(n.output[0], []) if k.op_type == 'Mul' and cur in k.input), None)
            assert mul is not None, 'Sigmoid not followed by Mul(x, sigmoid(x))'
            act = 1; cur = mul.output[0]
        elif n.op_type == 'Tanh' and cur == n.input[0]:
            out_tanh = True; cur = n.output[0]
        elif n.op_type == 'Split':
            split = True; cur = n.output[0]      # first output = mean
        elif n.op_type in ('Identity', 'Cast', 'Reshape', 'Flatten', 'Unsqueeze', 'Squeeze'):
            cur = n.output[0]
        else:
            raise SystemExit(f'unsupported op {n.op_type} on the running tensor')
    if split:
        W, b = layers[-1]; layers[-1] = (W[:out_dim], b[:out_dim])
    assert layers[0][0].shape[1] == in_dim and layers[-1][0].shape[0] == out_dim
    widths = [in_dim] + [W.shape[0] for W, _ in layers]
    nparams = sum(W.size + b.size for W, b in layers)
    def carr(name, arr):
        vals = ', '.join(f'{v:.8g}f' for v in arr.reshape(-1))
        return f'static const float {name}[{arr.size}] = {{ {vals} }};\n'
    L = [f'// Generated by tools/onnx_to_header.py from {a.onnx}\n// layers {"->".join(map(str, widths))}, {nparams} params ({nparams*4/1024:.0f} KB fp32)\n#pragma once\n',
         'struct PolicyLayer { int in; int out; const float* W; const float* b; };\n',
         f'#define POLICY_DESCRIPTION "{a.name or a.onnx}: {"->".join(map(str, widths))} act={["elu","swish","relu","tanh"][act]}{" split" if split else ""}{" tanh-out" if out_tanh else ""}"\n',
         f'#define POLICY_IN {in_dim}\n#define POLICY_OUT {out_dim}\n#define POLICY_NLAYERS {len(layers)}\n#define POLICY_MAX_WIDTH {max(widths)}\n',
         f'#define POLICY_ACT {act if act is not None else 2}\n#define POLICY_OUT_TANH {1 if out_tanh else 0}\n#define POLICY_OUT_SPLIT {1 if split else 0}\n',
         carr('POLICY_NORM_MEAN', mean), carr('POLICY_NORM_SCALE', scale)]
    for i, (W, b) in enumerate(layers):
        L.append(carr(f'POLICY_L{i}_W', W)); L.append(carr(f'POLICY_L{i}_B', b))
    L.append('static const PolicyLayer POLICY_LAYERS[POLICY_NLAYERS] = {\n' + ''.join(f'  {{ {W.shape[1]}, {W.shape[0]}, POLICY_L{i}_W, POLICY_L{i}_B }},\n' for i, (W, _) in enumerate(layers)) + '};\n')
    open(a.out, 'w').write(''.join(L))
    print(f'{a.out}: {"->".join(map(str, widths))} act={act} split={split} tanh={out_tanh} params={nparams}')
    # reference check against onnxruntime if present
    try:
        import onnxruntime as ort
        sess = ort.InferenceSession(a.onnx); x = np.random.RandomState(0).randn(1, in_dim).astype(np.float32)
        ref = sess.run(None, {inp.name: x})[0].reshape(-1)[:out_dim]
        h = (x.reshape(-1) - mean) * scale
        for i, (W, b) in enumerate(layers):
            h = W @ h + b
            if i < len(layers) - 1:
                h = {0: lambda v: np.where(v > 0, v, np.exp(v) - 1), 1: lambda v: v / (1 + np.exp(-v)), 2: lambda v: np.maximum(v, 0), None: lambda v: v}[act](h)
        if out_tanh: h = np.tanh(h)
        print('  max |header - onnxruntime| =', float(np.abs(h - ref).max()))
    except ImportError:
        print('  (onnxruntime not installed: numerical cross-check skipped)')
    except Exception as e:
        print('  cross-check failed:', e)

if __name__ == '__main__':
    main()
